INPUT:
  MIN_SIZE_TRAIN: 1000
DATALOADER:
  NUM_WORKERS: 0
FEATURE_MIMICKING:
  SAMPLES_PER_IMG: 32
  RESIZE: 224
  WEIGHT_COSINE: 0.1
  WEIGHT_CLS: 0.1
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "Deform-R-50-C5"
    C5_CHANNELS: 2048
    PRETRAINED_STEM_WEIGHTS: 'modeling/pretrained_weights/stem.pth'
    PRETRAINED_LAYER1_WEIGHTS: 'modeling/pretrained_weights/layer1.pth'     
  RESNETS:
    DEFORM_TRANS_FUNC: "DeformConvBottleneckWithGroupNorm"
  RPN:
    PRE_NMS_TOP_N_TRAIN: 12000
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    FG_IOU_THRESHOLD: 0.7
    MIN_SIZE: 16
  ROI_HEADS:
    COMBINED_ROI_HEADS: "DeformableCombinedROIHeads"
    POSITIVE_FRACTION: 0.35
  ROI_BOX_HEAD:
    CHANNELS_BEFORE_POOLING: 256
    DEFORM_POOLING_FC_CHANNELS: 1024
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 4
    DEFORM_POOLER_SCALES: 0.0625
    FEATURE_EXTRACTOR: "ResNet50DeformConv5ROIFeatureExtractor"
    FC_DIM: 1024
    PREDICTOR: "DeformFastRCNNPredictor"
  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
    CHANNELS_BEFORE_POOLING: 256
    DEFORM_POOLING_FC_CHANNELS: 1024
    SHARE_BOX_FEATURE_EXTRACTOR: False
    POOLER_RESOLUTION: 14
    RESOLUTION: 28
    POOLER_SAMPLING_RATIO: 4
    DEFORM_POOLER_SCALES: 0.0625
    FEATURE_EXTRACTOR: "MaskRCNNDeformableFeatureExtractor"
    FC_DIM: 1024
    PREDICTOR: "DeformMaskRCNNC5Predictor"
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0001
  STEPS: (2160000, 2880000)
  MAX_ITER: 3240000
  IMS_PER_BATCH: 1
  EVAL_NUM: 200
  CONF_THRES: 0.3
  BOARD_LOSS_INTERVAL: 100
  EVALUATE_INTERVAL: 4
  SAVE_INTERVAL: 10
  BOARD_IMAGE_INTERVAL: 5
  INFERENCE_INTERVAL: 1
  BOXREG_WEIGHT: 2
  OHEM: True
TEST:
  IMS_PER_BATCH: 2
  CONF_THRES: 0.7
  MIN_IMG_SIZE: 1000
WRITER_DIR: 'workspace/log'
WORKSPACE: 'workspace'
