MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "Deform-R-50-C5"
    C5_CHANNELS: 2048
  RESNETS:
    DEFORM_TRANS_FUNC: "DeformConvBottleneckWithGroupNorm"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    COMBINED_ROI_HEADS: "DeformableCombinedROIHeads"
  ROI_BOX_HEAD:
    CHANNELS_BEFORE_POOLING: 256
    DEFORM_POOLING_FC_CHANNELS: 1024
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 4
    DEFORM_POOLER_SCALES: 0.0625
    FEATURE_EXTRACTOR: "ResNet50DeformConv5ROIFeatureExtractor"
    FC_DIM: 1024
    PREDICTOR: "DeformFastRCNNPredictor"
  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
    CHANNELS_BEFORE_POOLING: 256
    DEFORM_POOLING_FC_CHANNELS: 1024
    SHARE_BOX_FEATURE_EXTRACTOR: False
    POOLER_RESOLUTION: 14
    RESOLUTION: 28
    POOLER_SAMPLING_RATIO: 4
    DEFORM_POOLER_SCALES: 0.0625
    FEATURE_EXTRACTOR: "MaskRCNNDeformableFeatureExtractor"
    FC_DIM: 1024
    PREDICTOR: "DeformMaskRCNNC5Predictor"
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 3
